version: '3.7'
services:
  db:
    image: prismagraphql/mongo-single-replica:4.4.3-bionic
    platform: linux/amd64
    ports:
      - 27016:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: monty
      MONGO_INITDB_ROOT_PASSWORD: pass
